//go:build !ignore_autogenerated

/*
Copyright 2023 The nagare media authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package dcterms

import (
	"github.com/nagare-media/models.go/dcmi/dc"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Abstract) DeepCopyInto(out *Abstract) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Abstract.
func (in *Abstract) DeepCopy() *Abstract {
	if in == nil {
		return nil
	}
	out := new(Abstract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRights) DeepCopyInto(out *AccessRights) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRights.
func (in *AccessRights) DeepCopy() *AccessRights {
	if in == nil {
		return nil
	}
	out := new(AccessRights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccrualMethod) DeepCopyInto(out *AccrualMethod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccrualMethod.
func (in *AccrualMethod) DeepCopy() *AccrualMethod {
	if in == nil {
		return nil
	}
	out := new(AccrualMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccrualPeriodicity) DeepCopyInto(out *AccrualPeriodicity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccrualPeriodicity.
func (in *AccrualPeriodicity) DeepCopy() *AccrualPeriodicity {
	if in == nil {
		return nil
	}
	out := new(AccrualPeriodicity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccrualPolicy) DeepCopyInto(out *AccrualPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccrualPolicy.
func (in *AccrualPolicy) DeepCopy() *AccrualPolicy {
	if in == nil {
		return nil
	}
	out := new(AccrualPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alternative) DeepCopyInto(out *Alternative) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alternative.
func (in *Alternative) DeepCopy() *Alternative {
	if in == nil {
		return nil
	}
	out := new(Alternative)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Audience) DeepCopyInto(out *Audience) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Audience.
func (in *Audience) DeepCopy() *Audience {
	if in == nil {
		return nil
	}
	out := new(Audience)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Available) DeepCopyInto(out *Available) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Available.
func (in *Available) DeepCopy() *Available {
	if in == nil {
		return nil
	}
	out := new(Available)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BibliographicCitation) DeepCopyInto(out *BibliographicCitation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BibliographicCitation.
func (in *BibliographicCitation) DeepCopy() *BibliographicCitation {
	if in == nil {
		return nil
	}
	out := new(BibliographicCitation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Box) DeepCopyInto(out *Box) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Box.
func (in *Box) DeepCopy() *Box {
	if in == nil {
		return nil
	}
	out := new(Box)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConformsTo) DeepCopyInto(out *ConformsTo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConformsTo.
func (in *ConformsTo) DeepCopy() *ConformsTo {
	if in == nil {
		return nil
	}
	out := new(ConformsTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Contributor) DeepCopyInto(out *Contributor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Contributor.
func (in *Contributor) DeepCopy() *Contributor {
	if in == nil {
		return nil
	}
	out := new(Contributor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coverage) DeepCopyInto(out *Coverage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coverage.
func (in *Coverage) DeepCopy() *Coverage {
	if in == nil {
		return nil
	}
	out := new(Coverage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Created) DeepCopyInto(out *Created) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Created.
func (in *Created) DeepCopy() *Created {
	if in == nil {
		return nil
	}
	out := new(Created)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Creator) DeepCopyInto(out *Creator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Creator.
func (in *Creator) DeepCopy() *Creator {
	if in == nil {
		return nil
	}
	out := new(Creator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DCMIType) DeepCopyInto(out *DCMIType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DCMIType.
func (in *DCMIType) DeepCopy() *DCMIType {
	if in == nil {
		return nil
	}
	out := new(DCMIType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DDC) DeepCopyInto(out *DDC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DDC.
func (in *DDC) DeepCopy() *DDC {
	if in == nil {
		return nil
	}
	out := new(DDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Date) DeepCopyInto(out *Date) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Date.
func (in *Date) DeepCopy() *Date {
	if in == nil {
		return nil
	}
	out := new(Date)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DateAccepted) DeepCopyInto(out *DateAccepted) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateAccepted.
func (in *DateAccepted) DeepCopy() *DateAccepted {
	if in == nil {
		return nil
	}
	out := new(DateAccepted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DateCopyrighted) DeepCopyInto(out *DateCopyrighted) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateCopyrighted.
func (in *DateCopyrighted) DeepCopy() *DateCopyrighted {
	if in == nil {
		return nil
	}
	out := new(DateCopyrighted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DateSubmitted) DeepCopyInto(out *DateSubmitted) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DateSubmitted.
func (in *DateSubmitted) DeepCopy() *DateSubmitted {
	if in == nil {
		return nil
	}
	out := new(DateSubmitted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Description) DeepCopyInto(out *Description) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Description.
func (in *Description) DeepCopy() *Description {
	if in == nil {
		return nil
	}
	out := new(Description)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EducationLevel) DeepCopyInto(out *EducationLevel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EducationLevel.
func (in *EducationLevel) DeepCopy() *EducationLevel {
	if in == nil {
		return nil
	}
	out := new(EducationLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Elements) DeepCopyInto(out *Elements) {
	*out = *in
	out.XMLName = in.XMLName
	if in.DCTitle != nil {
		in, out := &in.DCTitle, &out.DCTitle
		*out = make([]dc.Title, len(*in))
		copy(*out, *in)
	}
	if in.DCCreator != nil {
		in, out := &in.DCCreator, &out.DCCreator
		*out = make([]dc.Creator, len(*in))
		copy(*out, *in)
	}
	if in.DCSubject != nil {
		in, out := &in.DCSubject, &out.DCSubject
		*out = make([]dc.Subject, len(*in))
		copy(*out, *in)
	}
	if in.DCDescription != nil {
		in, out := &in.DCDescription, &out.DCDescription
		*out = make([]dc.Description, len(*in))
		copy(*out, *in)
	}
	if in.DCPublisher != nil {
		in, out := &in.DCPublisher, &out.DCPublisher
		*out = make([]dc.Publisher, len(*in))
		copy(*out, *in)
	}
	if in.DCContributor != nil {
		in, out := &in.DCContributor, &out.DCContributor
		*out = make([]dc.Contributor, len(*in))
		copy(*out, *in)
	}
	if in.DCDate != nil {
		in, out := &in.DCDate, &out.DCDate
		*out = make([]dc.Date, len(*in))
		copy(*out, *in)
	}
	if in.DCType != nil {
		in, out := &in.DCType, &out.DCType
		*out = make([]dc.Type, len(*in))
		copy(*out, *in)
	}
	if in.DCFormat != nil {
		in, out := &in.DCFormat, &out.DCFormat
		*out = make([]dc.Format, len(*in))
		copy(*out, *in)
	}
	if in.DCIdentifier != nil {
		in, out := &in.DCIdentifier, &out.DCIdentifier
		*out = make([]dc.Identifier, len(*in))
		copy(*out, *in)
	}
	if in.DCSource != nil {
		in, out := &in.DCSource, &out.DCSource
		*out = make([]dc.Source, len(*in))
		copy(*out, *in)
	}
	if in.DCLanguage != nil {
		in, out := &in.DCLanguage, &out.DCLanguage
		*out = make([]dc.Language, len(*in))
		copy(*out, *in)
	}
	if in.DCRelation != nil {
		in, out := &in.DCRelation, &out.DCRelation
		*out = make([]dc.Relation, len(*in))
		copy(*out, *in)
	}
	if in.DCCoverage != nil {
		in, out := &in.DCCoverage, &out.DCCoverage
		*out = make([]dc.Coverage, len(*in))
		copy(*out, *in)
	}
	if in.DCRights != nil {
		in, out := &in.DCRights, &out.DCRights
		*out = make([]dc.Rights, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Elements.
func (in *Elements) DeepCopy() *Elements {
	if in == nil {
		return nil
	}
	out := new(Elements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElementsAndTerms) DeepCopyInto(out *ElementsAndTerms) {
	*out = *in
	out.XMLName = in.XMLName
	in.Elements.DeepCopyInto(&out.Elements)
	in.Terms.DeepCopyInto(&out.Terms)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElementsAndTerms.
func (in *ElementsAndTerms) DeepCopy() *ElementsAndTerms {
	if in == nil {
		return nil
	}
	out := new(ElementsAndTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extent) DeepCopyInto(out *Extent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extent.
func (in *Extent) DeepCopy() *Extent {
	if in == nil {
		return nil
	}
	out := new(Extent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Format) DeepCopyInto(out *Format) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Format.
func (in *Format) DeepCopy() *Format {
	if in == nil {
		return nil
	}
	out := new(Format)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HasFormat) DeepCopyInto(out *HasFormat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HasFormat.
func (in *HasFormat) DeepCopy() *HasFormat {
	if in == nil {
		return nil
	}
	out := new(HasFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HasPart) DeepCopyInto(out *HasPart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HasPart.
func (in *HasPart) DeepCopy() *HasPart {
	if in == nil {
		return nil
	}
	out := new(HasPart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HasVersion) DeepCopyInto(out *HasVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HasVersion.
func (in *HasVersion) DeepCopy() *HasVersion {
	if in == nil {
		return nil
	}
	out := new(HasVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IMT) DeepCopyInto(out *IMT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IMT.
func (in *IMT) DeepCopy() *IMT {
	if in == nil {
		return nil
	}
	out := new(IMT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISO3166) DeepCopyInto(out *ISO3166) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISO3166.
func (in *ISO3166) DeepCopy() *ISO3166 {
	if in == nil {
		return nil
	}
	out := new(ISO3166)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISO639_2) DeepCopyInto(out *ISO639_2) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISO639_2.
func (in *ISO639_2) DeepCopy() *ISO639_2 {
	if in == nil {
		return nil
	}
	out := new(ISO639_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISO639_3) DeepCopyInto(out *ISO639_3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISO639_3.
func (in *ISO639_3) DeepCopy() *ISO639_3 {
	if in == nil {
		return nil
	}
	out := new(ISO639_3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identifier) DeepCopyInto(out *Identifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identifier.
func (in *Identifier) DeepCopy() *Identifier {
	if in == nil {
		return nil
	}
	out := new(Identifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstructionalMethod) DeepCopyInto(out *InstructionalMethod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstructionalMethod.
func (in *InstructionalMethod) DeepCopy() *InstructionalMethod {
	if in == nil {
		return nil
	}
	out := new(InstructionalMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsFormatOf) DeepCopyInto(out *IsFormatOf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsFormatOf.
func (in *IsFormatOf) DeepCopy() *IsFormatOf {
	if in == nil {
		return nil
	}
	out := new(IsFormatOf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsPartOf) DeepCopyInto(out *IsPartOf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsPartOf.
func (in *IsPartOf) DeepCopy() *IsPartOf {
	if in == nil {
		return nil
	}
	out := new(IsPartOf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsReferencedBy) DeepCopyInto(out *IsReferencedBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsReferencedBy.
func (in *IsReferencedBy) DeepCopy() *IsReferencedBy {
	if in == nil {
		return nil
	}
	out := new(IsReferencedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsReplacedBy) DeepCopyInto(out *IsReplacedBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsReplacedBy.
func (in *IsReplacedBy) DeepCopy() *IsReplacedBy {
	if in == nil {
		return nil
	}
	out := new(IsReplacedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsRequiredBy) DeepCopyInto(out *IsRequiredBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsRequiredBy.
func (in *IsRequiredBy) DeepCopy() *IsRequiredBy {
	if in == nil {
		return nil
	}
	out := new(IsRequiredBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsVersionOf) DeepCopyInto(out *IsVersionOf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsVersionOf.
func (in *IsVersionOf) DeepCopy() *IsVersionOf {
	if in == nil {
		return nil
	}
	out := new(IsVersionOf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Issued) DeepCopyInto(out *Issued) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Issued.
func (in *Issued) DeepCopy() *Issued {
	if in == nil {
		return nil
	}
	out := new(Issued)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCC) DeepCopyInto(out *LCC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCC.
func (in *LCC) DeepCopy() *LCC {
	if in == nil {
		return nil
	}
	out := new(LCC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCSH) DeepCopyInto(out *LCSH) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCSH.
func (in *LCSH) DeepCopy() *LCSH {
	if in == nil {
		return nil
	}
	out := new(LCSH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Language) DeepCopyInto(out *Language) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Language.
func (in *Language) DeepCopy() *Language {
	if in == nil {
		return nil
	}
	out := new(Language)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *License) DeepCopyInto(out *License) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new License.
func (in *License) DeepCopy() *License {
	if in == nil {
		return nil
	}
	out := new(License)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MESH) DeepCopyInto(out *MESH) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MESH.
func (in *MESH) DeepCopy() *MESH {
	if in == nil {
		return nil
	}
	out := new(MESH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mediator) DeepCopyInto(out *Mediator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mediator.
func (in *Mediator) DeepCopy() *Mediator {
	if in == nil {
		return nil
	}
	out := new(Mediator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Medium) DeepCopyInto(out *Medium) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Medium.
func (in *Medium) DeepCopy() *Medium {
	if in == nil {
		return nil
	}
	out := new(Medium)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Modified) DeepCopyInto(out *Modified) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Modified.
func (in *Modified) DeepCopy() *Modified {
	if in == nil {
		return nil
	}
	out := new(Modified)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLM) DeepCopyInto(out *NLM) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLM.
func (in *NLM) DeepCopy() *NLM {
	if in == nil {
		return nil
	}
	out := new(NLM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Period) DeepCopyInto(out *Period) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Period.
func (in *Period) DeepCopy() *Period {
	if in == nil {
		return nil
	}
	out := new(Period)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Point) DeepCopyInto(out *Point) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Point.
func (in *Point) DeepCopy() *Point {
	if in == nil {
		return nil
	}
	out := new(Point)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provenance) DeepCopyInto(out *Provenance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provenance.
func (in *Provenance) DeepCopy() *Provenance {
	if in == nil {
		return nil
	}
	out := new(Provenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Publisher) DeepCopyInto(out *Publisher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Publisher.
func (in *Publisher) DeepCopy() *Publisher {
	if in == nil {
		return nil
	}
	out := new(Publisher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RFC1766) DeepCopyInto(out *RFC1766) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RFC1766.
func (in *RFC1766) DeepCopy() *RFC1766 {
	if in == nil {
		return nil
	}
	out := new(RFC1766)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RFC3066) DeepCopyInto(out *RFC3066) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RFC3066.
func (in *RFC3066) DeepCopy() *RFC3066 {
	if in == nil {
		return nil
	}
	out := new(RFC3066)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RFC4646) DeepCopyInto(out *RFC4646) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RFC4646.
func (in *RFC4646) DeepCopy() *RFC4646 {
	if in == nil {
		return nil
	}
	out := new(RFC4646)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RFC5646) DeepCopyInto(out *RFC5646) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RFC5646.
func (in *RFC5646) DeepCopy() *RFC5646 {
	if in == nil {
		return nil
	}
	out := new(RFC5646)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *References) DeepCopyInto(out *References) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new References.
func (in *References) DeepCopy() *References {
	if in == nil {
		return nil
	}
	out := new(References)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Relation) DeepCopyInto(out *Relation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Relation.
func (in *Relation) DeepCopy() *Relation {
	if in == nil {
		return nil
	}
	out := new(Relation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replaces) DeepCopyInto(out *Replaces) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replaces.
func (in *Replaces) DeepCopy() *Replaces {
	if in == nil {
		return nil
	}
	out := new(Replaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requires) DeepCopyInto(out *Requires) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requires.
func (in *Requires) DeepCopy() *Requires {
	if in == nil {
		return nil
	}
	out := new(Requires)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rights) DeepCopyInto(out *Rights) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rights.
func (in *Rights) DeepCopy() *Rights {
	if in == nil {
		return nil
	}
	out := new(Rights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsHolder) DeepCopyInto(out *RightsHolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsHolder.
func (in *RightsHolder) DeepCopy() *RightsHolder {
	if in == nil {
		return nil
	}
	out := new(RightsHolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spatial) DeepCopyInto(out *Spatial) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spatial.
func (in *Spatial) DeepCopy() *Spatial {
	if in == nil {
		return nil
	}
	out := new(Spatial)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TGN) DeepCopyInto(out *TGN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TGN.
func (in *TGN) DeepCopy() *TGN {
	if in == nil {
		return nil
	}
	out := new(TGN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableOfContents) DeepCopyInto(out *TableOfContents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableOfContents.
func (in *TableOfContents) DeepCopy() *TableOfContents {
	if in == nil {
		return nil
	}
	out := new(TableOfContents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Temporal) DeepCopyInto(out *Temporal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Temporal.
func (in *Temporal) DeepCopy() *Temporal {
	if in == nil {
		return nil
	}
	out := new(Temporal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Terms) DeepCopyInto(out *Terms) {
	*out = *in
	out.XMLName = in.XMLName
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = make([]Title, len(*in))
		copy(*out, *in)
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = make([]Creator, len(*in))
		copy(*out, *in)
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = make([]Description, len(*in))
		copy(*out, *in)
	}
	if in.Publisher != nil {
		in, out := &in.Publisher, &out.Publisher
		*out = make([]Publisher, len(*in))
		copy(*out, *in)
	}
	if in.Contributor != nil {
		in, out := &in.Contributor, &out.Contributor
		*out = make([]Contributor, len(*in))
		copy(*out, *in)
	}
	if in.Date != nil {
		in, out := &in.Date, &out.Date
		*out = make([]Date, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = make([]Type, len(*in))
		copy(*out, *in)
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = make([]Format, len(*in))
		copy(*out, *in)
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = make([]Identifier, len(*in))
		copy(*out, *in)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = make([]Source, len(*in))
		copy(*out, *in)
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = make([]Language, len(*in))
		copy(*out, *in)
	}
	if in.Relation != nil {
		in, out := &in.Relation, &out.Relation
		*out = make([]Relation, len(*in))
		copy(*out, *in)
	}
	if in.Coverage != nil {
		in, out := &in.Coverage, &out.Coverage
		*out = make([]Coverage, len(*in))
		copy(*out, *in)
	}
	if in.Rights != nil {
		in, out := &in.Rights, &out.Rights
		*out = make([]Rights, len(*in))
		copy(*out, *in)
	}
	if in.Alternative != nil {
		in, out := &in.Alternative, &out.Alternative
		*out = make([]Alternative, len(*in))
		copy(*out, *in)
	}
	if in.TableOfContents != nil {
		in, out := &in.TableOfContents, &out.TableOfContents
		*out = make([]TableOfContents, len(*in))
		copy(*out, *in)
	}
	if in.Abstract != nil {
		in, out := &in.Abstract, &out.Abstract
		*out = make([]Abstract, len(*in))
		copy(*out, *in)
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = make([]Created, len(*in))
		copy(*out, *in)
	}
	if in.Valid != nil {
		in, out := &in.Valid, &out.Valid
		*out = make([]Valid, len(*in))
		copy(*out, *in)
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = make([]Available, len(*in))
		copy(*out, *in)
	}
	if in.Issued != nil {
		in, out := &in.Issued, &out.Issued
		*out = make([]Issued, len(*in))
		copy(*out, *in)
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = make([]Modified, len(*in))
		copy(*out, *in)
	}
	if in.DateAccepted != nil {
		in, out := &in.DateAccepted, &out.DateAccepted
		*out = make([]DateAccepted, len(*in))
		copy(*out, *in)
	}
	if in.DateCopyrighted != nil {
		in, out := &in.DateCopyrighted, &out.DateCopyrighted
		*out = make([]DateCopyrighted, len(*in))
		copy(*out, *in)
	}
	if in.DateSubmitted != nil {
		in, out := &in.DateSubmitted, &out.DateSubmitted
		*out = make([]DateSubmitted, len(*in))
		copy(*out, *in)
	}
	if in.Extent != nil {
		in, out := &in.Extent, &out.Extent
		*out = make([]Extent, len(*in))
		copy(*out, *in)
	}
	if in.Medium != nil {
		in, out := &in.Medium, &out.Medium
		*out = make([]Medium, len(*in))
		copy(*out, *in)
	}
	if in.IsVersionOf != nil {
		in, out := &in.IsVersionOf, &out.IsVersionOf
		*out = make([]IsVersionOf, len(*in))
		copy(*out, *in)
	}
	if in.HasVersion != nil {
		in, out := &in.HasVersion, &out.HasVersion
		*out = make([]HasVersion, len(*in))
		copy(*out, *in)
	}
	if in.IsReplacedBy != nil {
		in, out := &in.IsReplacedBy, &out.IsReplacedBy
		*out = make([]IsReplacedBy, len(*in))
		copy(*out, *in)
	}
	if in.Replaces != nil {
		in, out := &in.Replaces, &out.Replaces
		*out = make([]Replaces, len(*in))
		copy(*out, *in)
	}
	if in.IsRequiredBy != nil {
		in, out := &in.IsRequiredBy, &out.IsRequiredBy
		*out = make([]IsRequiredBy, len(*in))
		copy(*out, *in)
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]Requires, len(*in))
		copy(*out, *in)
	}
	if in.IsPartOf != nil {
		in, out := &in.IsPartOf, &out.IsPartOf
		*out = make([]IsPartOf, len(*in))
		copy(*out, *in)
	}
	if in.HasPart != nil {
		in, out := &in.HasPart, &out.HasPart
		*out = make([]HasPart, len(*in))
		copy(*out, *in)
	}
	if in.IsReferencedBy != nil {
		in, out := &in.IsReferencedBy, &out.IsReferencedBy
		*out = make([]IsReferencedBy, len(*in))
		copy(*out, *in)
	}
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]References, len(*in))
		copy(*out, *in)
	}
	if in.IsFormatOf != nil {
		in, out := &in.IsFormatOf, &out.IsFormatOf
		*out = make([]IsFormatOf, len(*in))
		copy(*out, *in)
	}
	if in.HasFormat != nil {
		in, out := &in.HasFormat, &out.HasFormat
		*out = make([]HasFormat, len(*in))
		copy(*out, *in)
	}
	if in.ConformsTo != nil {
		in, out := &in.ConformsTo, &out.ConformsTo
		*out = make([]ConformsTo, len(*in))
		copy(*out, *in)
	}
	if in.Spatial != nil {
		in, out := &in.Spatial, &out.Spatial
		*out = make([]Spatial, len(*in))
		copy(*out, *in)
	}
	if in.Temporal != nil {
		in, out := &in.Temporal, &out.Temporal
		*out = make([]Temporal, len(*in))
		copy(*out, *in)
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = make([]Audience, len(*in))
		copy(*out, *in)
	}
	if in.AccrualMethod != nil {
		in, out := &in.AccrualMethod, &out.AccrualMethod
		*out = make([]AccrualMethod, len(*in))
		copy(*out, *in)
	}
	if in.AccrualPeriodicity != nil {
		in, out := &in.AccrualPeriodicity, &out.AccrualPeriodicity
		*out = make([]AccrualPeriodicity, len(*in))
		copy(*out, *in)
	}
	if in.AccrualPolicy != nil {
		in, out := &in.AccrualPolicy, &out.AccrualPolicy
		*out = make([]AccrualPolicy, len(*in))
		copy(*out, *in)
	}
	if in.InstructionalMethod != nil {
		in, out := &in.InstructionalMethod, &out.InstructionalMethod
		*out = make([]InstructionalMethod, len(*in))
		copy(*out, *in)
	}
	if in.Provenance != nil {
		in, out := &in.Provenance, &out.Provenance
		*out = make([]Provenance, len(*in))
		copy(*out, *in)
	}
	if in.RightsHolder != nil {
		in, out := &in.RightsHolder, &out.RightsHolder
		*out = make([]RightsHolder, len(*in))
		copy(*out, *in)
	}
	if in.Mediator != nil {
		in, out := &in.Mediator, &out.Mediator
		*out = make([]Mediator, len(*in))
		copy(*out, *in)
	}
	if in.EducationLevel != nil {
		in, out := &in.EducationLevel, &out.EducationLevel
		*out = make([]EducationLevel, len(*in))
		copy(*out, *in)
	}
	if in.AccessRights != nil {
		in, out := &in.AccessRights, &out.AccessRights
		*out = make([]AccessRights, len(*in))
		copy(*out, *in)
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = make([]License, len(*in))
		copy(*out, *in)
	}
	if in.BibliographicCitation != nil {
		in, out := &in.BibliographicCitation, &out.BibliographicCitation
		*out = make([]BibliographicCitation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Terms.
func (in *Terms) DeepCopy() *Terms {
	if in == nil {
		return nil
	}
	out := new(Terms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Title) DeepCopyInto(out *Title) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Title.
func (in *Title) DeepCopy() *Title {
	if in == nil {
		return nil
	}
	out := new(Title)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Type) DeepCopyInto(out *Type) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Type.
func (in *Type) DeepCopy() *Type {
	if in == nil {
		return nil
	}
	out := new(Type)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDC) DeepCopyInto(out *UDC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDC.
func (in *UDC) DeepCopy() *UDC {
	if in == nil {
		return nil
	}
	out := new(UDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URI) DeepCopyInto(out *URI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URI.
func (in *URI) DeepCopy() *URI {
	if in == nil {
		return nil
	}
	out := new(URI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Valid) DeepCopyInto(out *Valid) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Valid.
func (in *Valid) DeepCopy() *Valid {
	if in == nil {
		return nil
	}
	out := new(Valid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *W3CDTF) DeepCopyInto(out *W3CDTF) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new W3CDTF.
func (in *W3CDTF) DeepCopy() *W3CDTF {
	if in == nil {
		return nil
	}
	out := new(W3CDTF)
	in.DeepCopyInto(out)
	return out
}
